name: music_channel
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  music_channel_web:
    path: ../music_channel_web
  music_channel_windows:
    path: ../music_channel_windows
  music_channel_macos:
    path: ../music_channel_macos
  music_platform_interface:
    path: ../music_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        default_package: music_channel_web
      windows:
        default_package: music_channel_windows
      macos:
        default_package: music_channel_macos